### ISSUE TITLE
Ни один клиент под винду не заработал.

### ISSUE THREAD

**Issue by x09** [altlinux/openuds-installers#2]
https://github.com/altlinux/openuds-installers/releases/download/3.0.0/openUDS-Client_Installer-3.0.0-py27.exe
![uds-client-py27-2021-11-24_14-54](https://user-images.githubusercontent.com/1303927/143216495-2df492e8-f16b-40fd-80e3-bdf7972124f6.png)

https://github.com/altlinux/openuds-installers/releases/download/3.0.0/openUDS-Client_Installer-3.0.0.exe
![openuds-client-3-2021-11-24_14-55](https://user-images.githubusercontent.com/1303927/143216504-3a279ce9-a92d-43aa-ad96-9d64ae9f3d29.png)

Windows 8.1 Про

Что делать?)

**Comment by august-alt** [comment]
Пожалуйста, добавьте лог %APPDATA%\..\Local\Temp\udsclient.log - что бы можно было провести более подробную диагностику.

**Comment by x09** [comment]
openUDS-Client_Installer-3.0.0-py27.exe
[udsclient.log](https://github.com/altlinux/openuds-installers/files/7594819/udsclient.log)

openUDS-Client_Installer-3.0.0.exe
не создал никакого лога

**Comment by august-alt** [comment]
Попробуйте эту версию клиента https://github.com/altlinux/openuds-installers/releases/download/3.0.0-alt1/openUDS-Client_Installer-3.0.0-alt1-py27.exe

Для того что бы работала версия python 3.9 под windows 8.1 необходимы установленные обновления:
Нужно установить KB3118401, для этого возможно понадобится сначала установить KB2919442 и KB2919355. 

Используется примерно следующий порядок установки пакетов обновлений:

KB2919442:
    Windows8.1-KB2919442-x64.msu

KB2919355:
    Windows8.1-KB2919355-x64.msu
    Windows8.1-KB2932046-x64.msu
    Windows8.1-KB2959977-x64.msu
    Windows8.1-KB2937592-x64.msu
    Windows8.1-KB2938439-x64.msu
    Windows8.1-KB2934018-x64.msu

KB3118401:
    Windows8.1-KB3118401-x64.msu

**Comment by august-alt** [comment]
Для отладки клиента с python3.9 на windows 8.1 я бы хотел получить лог установленных DLL которые загружет клиент. Для этого можно воспользоваться например http://dependencywalker.com/.

**Comment by x09** [comment]
> Попробуйте эту версию клиента https://github.com/altlinux/openuds-installers/releases/download/3.0.0-alt1/openUDS-Client_Installer-3.0.0-alt1-py27.exe
> 
> Для того что бы работала версия python 3.9 под windows 8.1 необходимы установленные обновления: Нужно установить KB3118401, для этого возможно понадобится сначала установить KB2919442 и KB2919355.
> 
> Используется примерно следующий порядок установки пакетов обновлений:
> 
> KB2919442: Windows8.1-KB2919442-x64.msu
> 
> KB2919355: Windows8.1-KB2919355-x64.msu Windows8.1-KB2932046-x64.msu Windows8.1-KB2959977-x64.msu Windows8.1-KB2937592-x64.msu Windows8.1-KB2938439-x64.msu Windows8.1-KB2934018-x64.msu
> 
> KB3118401: Windows8.1-KB3118401-x64.msu

все сделал, но результат тот же

KB3118401 вообще для вин7

**Comment by august-alt** [comment]
https://www.catalog.update.microsoft.com/Search.aspx?q=KB3118401 - Вот ссылка на каталог обновлений через него будет удобно найти обновления именно для windows 8.1. Вот прямая ссылка на обновление KB3118401 для windows 8.1 - https://www.microsoft.com/en-us/download/details.aspx?id=51109

**Comment by august-alt** [comment]
Приложите всё же лог dependencywalker, он поможет при отладке.

**Comment by august-alt** [comment]
Пришлите пожалуйста список обновлений на машине которую вы используете для запуска клиента:
Его можно получить командой:
```
wmic qfe list full /format:texttablewsys > "C:\hotfix.txt"
```

Это нужно для как можно точного воспроизведения тестового стенда.

**Comment by x09** [comment]
[hotfix.txt](https://github.com/altlinux/openuds-installers/files/7600251/hotfix.txt)

**Comment by x09** [comment]
![dep-walk-2021-11-25_09-38](https://user-images.githubusercontent.com/1303927/143380853-4007f09f-e77b-4531-aed6-810d1887bb1d.png)

[UDSClient.dwi.zip](https://github.com/altlinux/openuds-installers/files/7600263/UDSClient.dwi.zip

**Comment by august-alt** [comment]
Попробуйте, пожалуйста, обновлённую версию:
- https://github.com/altlinux/openuds-installers/releases/download/3.0.0-alt1/openUDS-Client_Installer-3.0.0-alt1.exe

**Comment by august-alt** [comment]
Обязательно удалите старую версию перед использованием новой.

**Comment by x09** [comment]
> Попробуйте, пожалуйста, обновлённую версию:
> 
> * https://github.com/altlinux/openuds-installers/releases/download/3.0.0-alt1/openUDS-Client_Installer-3.0.0-alt1.exe

Отлично. Заработало!

**Comment by x09** [comment]
но стабильность так себе)) 

![lo-win-2021-11-26_09-43](https://user-images.githubusercontent.com/1303927/143528006-b18066b7-b172-48c2-80c6-7b6d7b43f3bd.png)

**Comment by august-alt** [comment]
Без подробных логов и описания тестового стенда - который вы используете, по одному скриншоту трудно определить источник проблемы. Насколько я могу видеть из скриншота не работает сторонний компонент: VcXsrv - он не входит в openuds client.
